@startuml klondike--final-state
skinparam handwritten true

title Klondike. Initial State

object "Klondike:myKlondike" as myKlondike{
    nGame = 1
    status = 1
}

object "Goal:goal" as goal {
    status = true
}

object "Player:setilloPlayer" as player {
    id = 1
    name = 'Setillo'
}

object "Board:klondikeBoard" as board {

}


object "Stock:stockPile" as stockPile
object "Waste:wastePile" as wastePile

object stockPile {
    nCards = 0
}
object wastePile {
    nCards = 0
}


object "Foundation:diamondsFoundation" as diamondsFoundation {
    nCards = 13
}
object "Foundation:heartsFoundation" as heartsFoundation {
    nCards = 13
}

object "Foundation:spacesFoundation" as spacesFoundation {
    nCards = 13
}

object "Foundation:clubsFoundation" as clubsFoundation {
    nCards = 13
}

object "Card:card1" as card1 {  
    rank  = King
    faceUp = true
}

object "Card:card23" as card23 {
        rank  = Ace
        faceUp = true
}

object "Card:card24" as card24 {
        rank = King
        faceUp = true
}

object "Card:card25" as card25 {
        rank = King    
        faceUp = true
}

object "Card:card30" as card30 {  
    rank  = King
    faceUp = true
}

note bottom of tableauPile7
    7 total tableau piles
    Last card face up in each pile
    0, 1, 2, 3, 4, 5 & 6 face down cards in each pile, 
    repectively, from 1 to 7 pile
end note

note bottom of clubsFoundation
    4 total foundations piles
    with all cards
end note


object tableauPile1 {
    nCards = 0
}
object tableauPile7 {
    nCards = 0
}

object "Diamonds:diamondsSuite" as diamond {
    color = red
}
object "Hearst:heartsSuite" as hearts {
    color = red
}
object "Clubs:clubsSuite" as clubs {
    color = black
}

object "Spaces:spacesSuite" as spaces{
    color = black
}

object "Move:moveN" as moveN {
 
} 

myKlondike *--> player
myKlondike *--> goal
myKlondike *--> board

player --> goal

board *--> stockPile
board *--> wastePile
board *--> clubsFoundation
board *--> diamondsFoundation
board *--> heartsFoundation
board *--> spacesFoundation
board *--> tableauPile1
board *--> tableauPile7

diamondsFoundation o--> card1
spacesFoundation o--> card30
heartsFoundation o--> card23
clubsFoundation o--> card24

heartsFoundation o--> card25

card1  *--> diamond
card23 *--> hearts
card25 *--> hearts
card24 *--> clubs
card30 *--> spaces

player ..> moveN
moveN --> card1
moveN --> tableauPile7 : origin
moveN --> diamondsFoundation : destination
@enduml