@startuml klondike--vocabulary
skinparam handwritten true

title Klondike Vocabulary

class Klondike
class Player
class Goal
abstract Pile
class Stock
class Waste
class Foundation
class Tableau
class Card {
    faceUp: boolean
}
enum Rank {
    Ace,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine,
    Ten,
    Jack,
    Queen,
    King
}

abstract Suit
class Spades
class Hearts
class Diamonds
class Clubs

abstract Color
class Red
class Black

class Spades
class Clubs
class Diamonds
class Hearts

abstract Action
class Move
class TurnOver



Klondike *--> Player
Klondike *-right->  Board
Board    *--> "13x4" Card
Klondike *-->  Goal

Player ..> Action
Player --> Goal
Goal -> "4" Foundation

note right of Goal {
    A full suit in ascending order,
    for each foundation.
}


Action <|-- Move
Action <|-- TurnOver
Action -> Card
Move --> Pile : origin
Move --> Pile : destination
TurnOver --> Stock 
TurnOver --> Tableau 

Pile <|-down-- Stock
Pile <|-down-- Waste
Pile <|-down-- Tableau
Pile <|-down-- Foundation

Board *--> Stock
Board *--> Waste
Board *--> "7" Foundation
Board *--> "4" Tableau


Stock      o--> "0..24" Card 
Waste      o--> "0..24" Card
Tableau    o--> "0..13 " Card
Foundation o--> "     0..13" Card
Foundation --> Suit

Card *--> Rank
Card "1" *-right-> "1" Suit

Suit *-> Color
Suit  <|-- Hearts
Suit  <|-- Spades
Suit  <|-- Diamonds
Suit  <|-- Clubs
Color <|-- Red
Color <|-- Black

Diamonds *--> Red
Hearts   *--> Red
Clubs    *--> Black
Spades   *--> Black

@enduml