@startuml connect4--instructions

!theme mars

title Connect4 Instructions \n

state C1 <<choice>>
state InsertA as " "
state InsertB as " "
state InsertA2 as " "
state InsertB2 as " "

[*]      --> C1 
C1       --> InsertA : Player A insert
InsertA  --> InsertB : Player B insert
InsertB  --> C1 : [ totalCheckers < 6 ]
InsertB  --> InsertA2 : Player A insert
InsertA2 --> [*] : [ is4InLine ]
InsertA2 --> InsertB2 : Player B insert
InsertB2 --> [*] : [ is4InLine ]
InsertB2 --> InsertA2 : Player A insert

@enduml