@startuml connect4--instructions

!theme mars

title Connect4 Instructions \n

state A as " "
state InsertA as " "
state InsertB as " "
state InsertA2 as " "
state InsertB2 as " "

[*]      --> A 
A        --> InsertA : Player A \n insert
InsertA  --> InsertB : Player B \n insert
InsertB  --> A : [ insertedCheckers < 6 ]
InsertB  --> InsertA2 : Player A \n insert
InsertA2 --> [*] : [ is4InLine ]
InsertA2 --> InsertB2 : Player B \n insert
InsertB2 --> InsertA2 : Player A \n insert
InsertB2 --> [*] : [ isTiedGame]
InsertB2 --> [*] : [ is4InLine ]

@enduml