@startuml connect4--vocabulary


title Connect4 Vocabulary \n

class Connect4
class Turn
class Player
class Board
class Cell
class Checker
enum Color {
    Red,
    Yellow
}
class Insertion
class Goal
class 4InLineHorizontal
class 4InLineVertical
class 4InLineDiagonal

Connect4 *--> Turn
Connect4 *--> "    2" Player
Connect4 *--> Board

Turn --> " 2" Player
Player ---> "21" Checker
Player --> Goal
Player ..> "3..21" Insertion
Player -l-> Board

Board *-d-> "7x6" Cell
Cell o-r-> "0..1" Checker
Cell --> Column
Cell --> Row

Checker *--> Color
Insertion ---> Checker
Insertion --> Column

Goal --> "  4" Checker
Goal <|-down- 4InLineHorizontal
Goal <|-down- 4InLineVertical
Goal <|-down- 4InLineDiagonal



@enduml


' diagram Oscar Quintero, Borja Coll and Fernando Cortés ;-)
