@startuml connect4--vocabulary


title Connect4 Vocabulary \n

class Connect4
class Turn
class Player
class Board
class Cell
class Checker
enum Color {
    Red,
    Yellow
}
class Put
class Goal

class 4InLineHorizontal
class 4InLineVertical
class 4InLineDiagonal

Connect4 *-d-> "2 " Player
Connect4 *--> "7..42" Turn
Connect4 *--> Board
Connect4 *--> Goal

Turn --> Player
Player --> "21" Checker
Player o--> Goal
Player ..> Put

Board *---> "7x6" Cell
Cell o--> "0..1  " Checker

Cell --> Column
Cell --> Row

Checker *-d-> Color
Put --> Checker
Put --> Column

Goal ---> "4" Checker
Goal <|-down- 4InLineHorizontal
Goal <|-down- 4InLineVertical
Goal <|-down- 4InLineDiagonal



@enduml


' diagram Oscar Quintero, Borja Coll and Fernando Cortés ;-)
